#!/bin/bash

git clone git@github.com:zenrocklabs/zrchain.git
git clone git@github.com:zenrocklabs/zenrock.git
git clone git@github.com:zenrocklabs/zenbtc.git
git clone git@github.com:zenrocklabs/zenrock-avs.git
git clone git@github.com:zenrocklabs/zenrock-validators.git

